# Generated by Django 5.1 on 2024-11-29 21:27

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_classlevel_unique_together_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsubject",
            name="class_level",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.classlevel",
            ),
        ),
    ]
