# Generated by Django 5.1 on 2024-10-15 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_meangradeconfig"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(default=0)),
                (
                    "source_class_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_promotion_records",
                        to="main.classlevel",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "target_class_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_promotion_records",
                        to="main.classlevel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
