# Generated by Django 5.1 on 2024-10-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_promotionrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="birth_date",
        ),
        migrations.AddField(
            model_name="student",
            name="kcpe_marks",
            field=models.IntegerField(default=0),
        ),
    ]
