# Generated by Django 5.1 on 2024-11-06 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_student_status_graduationrecord"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="graduationrecord",
            unique_together={("student", "graduation_year")},
        ),
    ]
