# Generated by Django 5.1 on 2024-11-09 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_meangradeconfig"),
        ("students", "0005_alter_graduationrecord_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="current_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.term",
            ),
        ),
    ]
