# Generated by Django 5.1 on 2024-12-17 02:59

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_term_class_levels_term_class_level'),
        ('students', '0005_alter_studentsubject_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classlevel'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='class_level',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='main.classlevel'),
        ),
    ]
