# Generated by Django 5.1 on 2024-11-17 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_term_end_date_remove_term_start_date_and_more"),
        ("students", "0006_student_current_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="current_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.term"
            ),
        ),
    ]
