# Generated by Django 5.1 on 2024-12-19 00:01

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_meangradeconfig_principal_remarks'),
        ('students', '0008_alter_studentsubject_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='class_level',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='main.classlevel'),
        ),
    ]
