# Generated by Django 5.1 on 2024-11-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
