# Generated by Django 5.1 on 2025-01-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Principal', 'Principal'), ('Secretary', 'Secretary')], default='Admin', max_length=20),
        ),
    ]
