# Generated by Django 5.1 on 2024-09-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachersubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachersubject_set",
                to="teachers.teacher",
            ),
        ),
    ]
