# Generated by Django 5.1 on 2024-11-22 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0003_alter_teachersubject_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
