# Generated by Django 5.1 on 2025-01-22 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_alter_classlevel_calendar_year'),
        ('students', '0005_alter_studentsubject_class_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm'), ('Endterm', 'Endterm'), ('Quiz', 'Quiz'), ('Practical', 'Practical')], max_length=20)),
                ('total_score', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('student_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsubject')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.term')),
            ],
            options={
                'unique_together': {('student', 'student_subject', 'term', 'exam_type')},
            },
        ),
    ]
