# Generated by Django 5.1 on 2024-10-08 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
        ("main", "0005_alter_term_calendar_year"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marksdata",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="marksdata",
            name="term",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.term"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marksdata",
            unique_together={("student", "student_subject", "term")},
        ),
    ]
