# Generated by Django 5.1 on 2024-11-29 00:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=10, unique=True)),
                ("level", models.IntegerField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeanGradeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.CharField(max_length=255)),
                ("min_mean_marks", models.FloatField(default=0)),
                ("max_mean_marks", models.FloatField(default=0)),
                ("remarks", models.CharField(max_length=255)),
                ("points", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("grade",)},
            },
        ),
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.formlevel"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.stream",
                    ),
                ),
            ],
            options={
                "unique_together": {("stream", "form_level")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_name", models.CharField(max_length=50, unique=True)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("Core", "Core"), ("Elective", "Elective")],
                        default="Core",
                        max_length=20,
                    ),
                ),
                (
                    "class_levels",
                    models.ManyToManyField(
                        related_name="subjects", to="main.classlevel"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.subjectcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("Term 1", "Term 1"),
                            ("Term 2", "Term 2"),
                            ("Term 3", "Term 3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calendar_year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Ended", "Ended"),
                            ("Upcoming", "Upcoming"),
                        ],
                        default="Active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "unique_together": {("term", "calendar_year")},
            },
        ),
        migrations.CreateModel(
            name="GradingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.CharField(max_length=255)),
                ("min_marks", models.FloatField(default=0)),
                ("max_marks", models.FloatField(default=0)),
                ("remarks", models.CharField(max_length=255)),
                ("points", models.IntegerField(default=0)),
                (
                    "subject_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.subjectcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("grade", "subject_category")},
            },
        ),
    ]
