# Generated by Django 5.1 on 2024-12-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
