# Generated by Django 5.1 on 2024-11-29 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classlevel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="classlevel",
            name="calendar_year",
            field=models.IntegerField(
                help_text="Enter a valid year.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2034),
                ],
            ),
        ),
        migrations.AddField(
            model_name="classlevel",
            name="terms",
            field=models.ManyToManyField(related_name="class_levels", to="main.term"),
        ),
        migrations.AddField(
            model_name="term",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="term",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="classlevel",
            unique_together={("stream", "form_level", "calendar_year")},
        ),
        migrations.RemoveField(
            model_name="term",
            name="calendar_year",
        ),
    ]
