# Generated by Django 5.1 on 2024-09-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="class_levels",
            field=models.ManyToManyField(related_name="subjects", to="main.classlevel"),
        ),
    ]
