# Generated by Django 5.1 on 2024-12-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_classlevel_level_alter_classlevel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meangradeconfig',
            old_name='max_mean_marks',
            new_name='max_mean_points',
        ),
        migrations.RenameField(
            model_name='meangradeconfig',
            old_name='min_mean_marks',
            new_name='min_mean_points',
        ),
        migrations.RemoveField(
            model_name='meangradeconfig',
            name='points',
        ),
    ]
