# Generated by Django 5.1 on 2024-11-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_classlevel_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="term",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
