# Generated by Django 5.1 on 2024-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_max_mean_marks_meangradeconfig_max_mean_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meangradeconfig',
            name='max_mean_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='meangradeconfig',
            name='min_mean_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
