# Generated by Django 5.1 on 2024-10-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_gradingconfig_unique_together_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="calendar_year",
            field=models.IntegerField(default=2024, editable=False),
        ),
    ]
