# Generated by Django 5.1 on 2024-11-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_term_end_date_alter_term_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classlevel",
            name="terms",
        ),
        migrations.AddField(
            model_name="term",
            name="class_levels",
            field=models.ManyToManyField(
                blank=True, related_name="terms", to="main.classlevel"
            ),
        ),
    ]
