# Generated by Django 5.1 on 2024-10-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_term_calendar_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="calendar_year",
            field=models.IntegerField(),
        ),
    ]
