# Generated by Django 5.1 on 2024-11-30 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_classlevel_terms_term_class_levels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="term",
            name="class_levels",
        ),
        migrations.AddField(
            model_name="term",
            name="class_level",
            field=models.ForeignKey(
                default=2025,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms",
                to="main.classlevel",
            ),
            preserve_default=False,
        ),
    ]
