# Generated by Django 5.1 on 2025-01-22 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_meangradeconfig_max_mean_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='calendar_year',
            field=models.IntegerField(help_text='Enter a valid year.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2035)]),
        ),
    ]
