# Generated by Django 5.1 on 2024-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_term_class_levels_term_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='meangradeconfig',
            name='principal_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
