# Generated by Django 5.1.1 on 2024-10-09 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_term_calendar_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeanGradeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.CharField(max_length=255)),
                ("min_mean_marks", models.FloatField(default=0)),
                ("max_mean_marks", models.FloatField(default=0)),
                ("remarks", models.CharField(max_length=255)),
                ("points", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("grade",)},
            },
        ),
    ]
