# Generated by Django 5.1 on 2024-12-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_meangradeconfig_principal_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meangradeconfig',
            name='principal_remarks',
            field=models.CharField(max_length=255),
        ),
    ]
