# Generated by Django 5.1.1 on 2024-11-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_meangradeconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="term",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
