# Generated by Django 5.1 on 2024-11-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_term_end_date_term_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="term",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="term",
            name="start_date",
        ),
        migrations.AddField(
            model_name="term",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Ended", "Ended"),
                    ("Upcoming", "Upcoming"),
                ],
                default="Active",
                max_length=10,
            ),
        ),
    ]
