# Generated by Django 5.1 on 2024-12-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_meangradeconfig_principal_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meangradeconfig',
            name='principal_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
