# Generated by Django 5.1 on 2024-11-22 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_term_end_date_remove_term_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classlevel",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="classlevel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
